export const departements = [
  "01 Ain",
  "02 Aisne",
  "03 Allier",
  "04 Alpes-de-Haute-Provence",
  "05 Hautes-Alpes",
  "06 Alpes-Maritimes",
  "07 Ardèche",
  "08 Ardennes",
  "09 Ariège",
  "10 Aube",
  "11 Aude",
  "12 Aveyron",
  "13 Bouches-du-Rhône",
  "14 Calvados",
  "15 Cantal",
  "16 Charente",
  "17 Charente-Maritime",
  "18 Cher",
  "19 Corrèze",
  "2A Corse-du-Sud",
  "2B Corse-Haute",
  "21 Côte-d'Or",
  "22 Côtes-d'Armor",
  "23 Creuse",
  "24 Dordogne",
  "25 Doubs",
  "26 Drôme",
  "27 Eure",
  "28 Eure-et-Loir",
  "29 Finistère",
  "30 Gard",
  "31 Haute-Garonne",
  "32 Gers",
  "33 Gironde",
  "34 Hérault",
  "35 Ille-et-Vilaine",
  "36 Indre",
  "37 Indre-et-Loire",
  "38 Isère",
  "39 Jura",
  "40 Landes",
  "41 Loir-et-Cher",
  "42 Loire",
  "43 Haute-Loire",
  "44 Loire-Atlantique",
  "45 Loiret",
  "46 Lot",
  "47 Lot-et-Garonne",
  "48 Lozère",
  "49 Maine-et-Loire",
  "50 Manche",
  "51 Marne",
  "52 Haute-Marne",
  "53 Mayenne",
  "54 Moselle",
  "55 Meuse",
  "56 Morbihan",
  "57 Meurthe-et-Moselle",
  "58 Nièvre",
  "59 Nord",
  "60 Oise",
  "61 Orne",
  "62 Pas-de-Calais",
  "63 Puy-de-Dôme",
  "64 Pyrénées-Atlantiques",
  "65 Hautes-Pyrénées",
  "66 Pyrénées-Orientales",
  "67 Bas-Rhin",
  "68 Haut-Rhin",
  "69 Rhône",
  "70 Haute-Saône",
  "71 Saône-et-Loire",
  "72 Sarthe",
  "73 Savoie",
  "74 Haute-Savoie",
  "75 Paris",
  "76 Seine-Maritime",
  "77 Seine-et-Marne",
  "78 Yvelines",
  "79 Deux-Sèvres",
  "80 Somme",
  "81 Tarn",
  "82 Tarn-et-Garonne",
  "83 Var",
  "84 Vaucluse",
  "85 Vendée",
  "86 Vienne",
  "87 Haute-Vienne",
  "88 Vosges",
  "89 Yonne",
  "90 Territoire de Belfort",
  "91 Essonne",
  "92 Hauts-de-Seine",
  "93 Seine-Saint-Denis",
  "94 Val-de-Marne",
  "95 Val-d'Oise",
  "Guadeloupe",
  "Martinique",
  "Guyane",
  "La Réunion",
  "Mayotte",
];

export const countries = [
  "Afghanistan",
  "Afrique du Sud",
  "Albanie",
  "Algérie",
  "Allemagne",
  "Andorre",
  "Angola",
  "Antigua-et-Barbuda",
  "Arabie Saoudite",
  "Argentine",
  "Arménie",
  "Australie",
  "Autriche",
  "Azerbaïdjan",
  "Bahamas",
  "Bahreïn",
  "Bangladesh",
  "Barbade",
  "Belgique",
  "Belize",
  "Bénin",
  "Bhoutan",
  "Biélorussie",
  "Bolivie",
  "Bosnie-Herzégovine",
  "Botswana",
  "Brésil",
  "Brunei",
  "Bulgarie",
  "Burkina Faso",
  "Burundi",
  "Cambodge",
  "Cameroun",
  "Canada",
  "Cap-Vert",
  "Chili",
  "Chine",
  "Chypre",
  "Colombie",
  "Comores",
  "Congo",
  "Corée du Nord",
  "Corée du Sud",
  "Costa Rica",
  "Côte d'Ivoire",
  "Croatie",
  "Cuba",
  "Danemark",
  "Djibouti",
  "République Dominicaine",
  "Dominique",
  "Égypte",
  "Émirats Arabes Unis",
  "Équateur",
  "Érythrée",
  "Espagne",
  "Estonie",
  "États-Unis",
  "Éthiopie",
  "Fidji",
  "Finlande",
  "Gabon",
  "Gambie",
  "Géorgie",
  "Ghana",
  "Grèce",
  "Grenade",
  "Guatemala",
  "Guinée",
  "Guinée-Bissau",
  "Guinée équatoriale",
  "Guyana",
  "Haïti",
  "Honduras",
  "Hongrie",
  "Inde",
  "Indonésie",
  "Irak",
  "Iran",
  "Irlande",
  "Islande",
  "Israël",
  "Italie",
  "Jamaïque",
  "Japon",
  "Jordanie",
  "Kazakhstan",
  "Kenya",
  "Kirghizistan",
  "Kiribati",
  "Koweït",
  "Laos",
  "Lesotho",
  "Lettonie",
  "Liban",
  "Liberia",
  "Libye",
  "Liechtenstein",
  "Lituanie",
  "Luxembourg",
  "Macédoine",
  "Madagascar",
  "Malaisie",
  "Malawi",
  "Maldives",
  "Mali",
  "Malte",
  "Maroc",
  "Marshall",
  "Maurice",
  "Mauritanie",
  "Mexique",
  "Micronésie",
  "Moldavie",
  "Monaco",
  "Mongolie",
  "Monténégro",
  "Mozambique",
  "Myanmar",
  "Namibie",
  "Nauru",
  "Népal",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norvège",
  "Nouvelle-Zélande",
  "Oman",
  "Ouganda",
  "Ouzbékistan",
  "Pakistan",
  "Palaos",
  "Palestine",
  "Panama",
  "Papouasie-Nouvelle-Guinée",
  "Paraguay",
  "Pays-Bas",
  "Pérou",
  "Philippines",
  "Pologne",
  "Portugal",
  "Qatar",
  "Roumanie",
  "Royaume-Uni",
  "Russie",
  "Rwanda",
  "Saint-Christophe-et-Niévès",
  "Sainte-Lucie",
  "Saint-Marin",
  "Saint-Siège",
  "Saint-Vincent-et-les-Grenadines",
  "Salomon",
  "Salvador",
  "Samoa",
  "Sao Tomé-et-Principe",
  "Sénégal",
  "Serbie",
  "Seychelles",
  "Sierra Leone",
  "Singapour",
  "Slovaquie",
  "Slovénie",
  "Somalie",
  "Soudan",
  "Sri Lanka",
  "Suède",
  "Suisse",
  "Suriname",
  "Swaziland",
  "Syrie",
  "Tadjikistan",
  "Tanzanie",
  "Tchad",
  "Tchèque",
  "Thaïlande",
  "Timor oriental",
  "Togo",
  "Tonga",
  "Trinité-et-Tobago",
  "Tunisie",
  "Turkménistan",
  "Turquie",
  "Tuvalu",
  "Ukraine",
  "Uraguay",
  "Vanuatu",
  "Vatican",
  "Venezuela",
  "Viêt Nam",
  "Yémen",
  "Zambie",
  "Zimbabwe",
];
